### ISSUE TITLE
Support for check_quant=False when loading wdls

### ISSUE THREAD

**Issue by aclum** [stjudecloud/wdldoc#115]
A lot of our workflows have optional inputs and using wdldoc fails to create documentation for these workflows with an import error. Would it be possible to add an option to pass check_quant=False to wdl.load?

example error
`[E 230126 16:47:23 wdldoc:67] ImportError: Failed to import cds_prediction.wdl`

When i try directly with  
`wdl.load("cds_prediction.wdl")`
I get a try error
`WDL.Error.StaticTypeMismatch: Expected String instead of String? -- to coerce T? X into T, try select_first([X,defaultValue]) or select_first([X]) (which might fail at runtime); to coerce Array[T?] X into Array[T], try select_all(X)`

If I add check_quant=False the wdl loads w/o a problem

```
>>> wdl.load("cds_prediction.wdl",check_quant=False)
<WDL.Tree.Document object at 0x155552dc3a60>
```

**Comment by a-frantz** [comment]
While enabling a `--no-quant-check` in WDLdoc would likely be straightforward, the recent WDL specification disallows the coercions your code is attempting. `miniwdl` declares the argument to be "discouraged", so we would prefer not to port it to WDLdoc. Instead, we recommend updating the workflows to remove the disallowed coercions.
