### ISSUE TITLE
add command to the rendered doc 

### ISSUE THREAD

**Issue by sidwekhande** [stjudecloud/wdldoc#249]
Hi team,

Thank you for your work on `wdldoc`! We are very interested in using this tool to document our WDL workflows. 
A feature I would like to request is the inclusion of the `command` WDL section in the rendered doc. This will allow our users to know the exact commands that are run, without the need to dig through the code.

**Comment by a-frantz** [comment]
Hi there! Thanks for the interest in `wdldoc`! This repo hasn't been officially deprecated, but it will be soon. We haven't been actively developing this tool for a while now, and we have plans to add a `sprocket doc` command to [sprocket](https://github.com/stjude-rust-labs/sprocket). `sprocket doc` should be better in just about every way to `wdldoc`, so please follow along on that repo for developments!
