### ISSUE TITLE
Request: support for struct documentation

### ISSUE THREAD

**Issue by matthdsm** [stjudecloud/wdldoc#5]
Hi,

Would it be possible to add support to auto-document structs? We have workflows/tasks that take custom structs as inputs, but as of now, these inputs are somewhat undocumented due to the missing struct support.

Thanks
M

**Comment by a-frantz** [comment]
That's definitely something we can add to a future release. Would you be able to link me where/how you use it? I haven't seen a WDL struct outside of the specification before, and think an example would be helpful in thinking how to structure the docs.

**Comment by matthdsm** [comment]
Sure! You can use the broad workflows as an example. There they have all the [structs in a separate file](https://github.com/broadinstitute/warp/blob/develop/structs/dna_seq/DNASeqStructs.wdl). Those structs are then later used as custom input and output "types", as seen [here](https://github.com/broadinstitute/warp/blob/develop/pipelines/broad/dna_seq/germline/single_sample/exome/ExomeGermlineSingleSample.wdl#L45).

Hope this makes things more clear.
M

**Comment by a-frantz** [comment]
Sorry about making you wait so long on this! Totally slipped off my radar till the bot pinged me about it.

The examples you linked will be good for testing, I think we're good there. But can you provide some details about how you'd like the structs rendered into markdown? I'm pretty agnostic about how they end up looking as we don't use them, but want to make sure my implementation fits expectations.

**Comment by matthdsm** [comment]
Hi Andrew,

Sorry to say, but I don't really remember much anymore 😅  We've since moved away from WDL and started using Nextflow.
Feel free to close this and or implement this to your liking.

Cheers and thanks for answering.
Matthias

**Comment by a-frantz** [comment]
Thanks for letting me know!
