### ISSUE TITLE
Support for WDL development version

### ISSUE THREAD

**Issue by matthdsm** [stjudecloud/wdldoc#6]
Hi,

Is there any support planned for WDL v1.1 and above?
I've got some WDL's in written in `version development` for which wdldoc reports validation error, but pass in `womtool validate`

Thanks
M

**Comment by a-frantz** [comment]
Give the [newest release](https://github.com/stjudecloud/wdldoc/releases/tag/v1.7.1) a try. Development on this halted before v1.1 was released, so the version of `miniwdl` we had pegged didn't know how to parse any of those new features.

I just updated the `miniwdl` version, so it should correctly validate your WDL now.

If there's any unexpected behavior, or any WDL is incorrectly documented, let us know. We're not currently developing in WDL v1.1 (or development), so we won't know if anything is amiss.

Thanks,
-Andrew

**Comment by matthdsm** [comment]
Hi,

True! I've updated everything to the latest version and all is well.
Thanks
M
